COURSE = {
    "title": "DevOps Roadmap",
    "year": "2026",
    "tagline": "Esto es DevOps.",
    "lede": "Un curso para aprender a construir, publicar y operar software con criterio. Piso bajo, techo alto: se puede empezar sin experiencia y terminar pensando como ingeniera o ingeniero de plataformas.",
    "authors": "Basado en el DevOps Roadmap 2026 de Dr. Milan Milanović y Romano Roth (TechWorld With Milan).",
    "weeks_label": "12 semanas + un bonus",
}

WEEKS = []


def W(**kwargs):
    WEEKS.append(kwargs)


W(
    id="01",
    num=1,
    title="Git",
    hours="6–10 h",
    skills=["Comandos base", "Pull request", "Ramas", "Fusión"],
    goal="Dejar de temerle al historial. Toda tu aplicación y tu infraestructura vivirán en un repositorio.",
    why="En DevOps no hay magia fuera del repositorio. El código de la app, los pipelines, los manifiestos y Terraform son archivos. Si no controlas el cambio, no controlas la producción.",
    lecture=[
        ("h2", "La caja negra"),
        ("p", "Git no es GitHub. Git es un motor local de instantáneas. GitHub, GitLab y similares son plazas públicas donde esas instantáneas se revisan, se discuten y se despliegan. Primero entiende el motor; después la plaza."),
        ("p", "Cada commit es una foto del proyecto en un instante, con un autor, un mensaje y un padre. Una rama es solo un puntero móvil a un commit. Fusionar es hacer que dos historias vuelvan a ser una."),
        ("callout", "Abstracción CS50", "Trata Git como una máquina de tiempo con nombres. clone copia el universo. branch crea una línea de tiempo paralela. merge las reconcilia. pull request es el ritual social para no fusionar a ciegas."),
        ("h2", "Lo que debes saber hacer"),
        ("ul", [
            "Clonar, ver el estado, agregar, confirmar y enviar cambios.",
            "Crear ramas con propósito: una idea, una rama.",
            "Abrir una solicitud de cambio (pull request) y responder revisión.",
            "Fusionar, rebasear con cuidado y resolver conflictos sin pánico.",
            "Entender que la infraestructura también es código versionado.",
        ]),
        ("h2", "Comandos que sí vas a usar"),
        ("code", "bash", "git clone <url>\ngit status\ngit add .\ngit commit -m \"Explica el porqué, no el qué\"\ngit switch -c feature/dns-ttl\ngit push -u origin HEAD\ngit log --oneline --graph"),
        ("h2", "Ramas, fusión y pull requests"),
        ("p", "Una rama barata te permite experimentar. El pull request no es burocracia: es el momento en que otro cerebro lee tu cambio antes de que toque main. Ahí se discute correctitud, diseño y estilo — la misma rúbrica de este curso."),
        ("p", "Fusionar (merge) conserva la historia de la rama. Rebasear reescribe para que parezca lineal. En equipos, prefiere merge o squash según la convención del repositorio; no improvises en main."),
        ("h2", "Errores comunes"),
        ("ul", [
            "Commits gigantes que mezclan formato, lógica y secretos.",
            "Subir .env, llaves SSH o kubeconfig. Eso no se borra del historial con un commit nuevo.",
            "Trabajar directo en main y luego pelear con todo el mundo.",
        ]),
    ],
    shorts=[
        ("Commit", "Un commit es un objeto inmutable. Si cambias la historia, creas commits nuevos. Por eso force-push en ramas compartidas duele."),
        ("Rama", "main, develop o trunk son convenciones, no magia. El servidor no sabe cuál es sagrada hasta que tú proteges la rama."),
        ("Pull request", "Es una conversación con diff. El botón verde es un despliegue social: alguien apuesta a que esto no rompe producción."),
        ("Conflicto", "Git te pide que elijas líneas. El conflicto no es un error de Git: es dos verdades sobre el mismo archivo."),
    ],
    walkthrough=[
        "Instala Git y configura user.name y user.email.",
        "Crea un repositorio vacío y haz tres commits pequeños con mensajes claros.",
        "Abre una rama, cambia un archivo, publícala y abre un pull request.",
        "Fusiona el PR y observa el grafo con git log --graph.",
    ],
    pset_std=[
        ("Hello, Git", "Crea un repositorio local llamado bitacora. Documenta en README.md qué es DevOps en cinco líneas. Tres commits, no uno."),
        ("Línea de tiempo", "Crea la rama experimento, cambia el README, vuelve a main y fusiónala. Deja evidencia del grafo."),
        ("La plaza", "Sube el repo a GitHub o GitLab. Abre un PR aunque seas la única persona. Revísalo en la interfaz."),
        ("Higiene", "Añade un .gitignore para .env, __pycache__/, node_modules/ y *.pem. Confirma que git status queda limpio."),
    ],
    pset_hack=[
        ("Arqueología", "Usa git bisect o git blame en un repo público pequeño para encontrar el commit que introdujo una línea concreta."),
        ("Historia peligrosa", "Aprende git revert frente a git reset. Escribe cuándo usar cada uno. Nunca hagas reset --hard en main compartida."),
    ],
    quiz=[
        ("¿Qué es Git, en una frase?",
         ["Un hosting de código en la nube", "Un sistema de control de versiones distribuido", "Un pipeline de CI", "Un servidor Linux"],
         1, "Git funciona en tu máquina. GitHub es un hosting. CI es otra capa."),
        ("Una rama es, sobre todo:",
         ["Una copia completa del disco", "Un puntero a un commit", "Un usuario del equipo", "Un contenedor"],
         1, "Las ramas son baratas porque son nombres, no duplicados pesados."),
        ("¿Para qué sirve un pull request?",
         ["Compilar el kernel", "Revisar y discutir un cambio antes de fusionarlo", "Borrar el historial", "Crear un clúster"],
         1, "El PR es revisión humana más automatización."),
        ("¿Dónde debe vivir la infraestructura como código?",
         ["En un wiki", "En el mismo tipo de repositorio Git que la aplicación", "Solo en la consola del cloud", "En un USB"],
         1, "Si no está en Git, no es reproducible."),
    ],
    feynman="Explícale Git a alguien que nunca ha programado: qué problema resuelve, qué es un commit y por qué no trabajamos todos sobre el mismo archivo a la vez.",
    flash=[
        ("¿Git es lo mismo que GitHub?", "No. Git es el motor local de versiones. GitHub o GitLab son plazas públicas para revisar y publicar esas versiones."),
        ("¿Qué es un commit?", "Una instantánea inmutable del proyecto, con mensaje, autor y padre."),
        ("¿Qué es una rama en Git?", "Un puntero móvil a un commit. Es un nombre, no una copia pesada del disco."),
        ("Nombra comandos base de Git", "clone, status, add, commit, switch/branch, merge, push y pull."),
        ("¿Para qué sirve un pull request?", "Para revisar correctitud, diseño y estilo antes de tocar la rama principal."),
    ],
    resources=[
        ("Atlassian Git tutorials", "https://www.atlassian.com/git", "Gratis"),
        ("Learn Git Branching", "https://learngitbranching.js.org/", "Interactivo"),
        ("Pro Git (libro)", "https://git-scm.com/book/en/v2", "Gratis"),
        ("Codecademy Learn Git", "https://www.codecademy.com/learn/learn-git", "Curso"),
        ("Git Immersion", "https://gitimmersion.com/index.html", "Gratis"),
    ],
    rubric=("El historial se puede leer de atrás hacia adelante.",
            "Cada commit hace una sola cosa.",
            "Mensajes en imperativo, sin ruido, sin secretos."),
)

W(
    id="02",
    num=2,
    title="Un lenguaje de programación",
    hours="10–16 h",
    skills=["Python", "Go", "JavaScript"],
    goal="Escribir automatización, no solo pulsar botones. Elige un lenguaje y llévalo a la fluidez básica.",
    why="DevOps sin código es un operador eterno. Con un lenguaje puedes convertir un ritual de 40 clics en un script revisable, testeable y versionado.",
    lecture=[
        ("h2", "Elige uno. Domínalo."),
        ("p", "Python, Go y JavaScript son los más comunes en este oficio. Python brilla en scripts, APIs y pegamento. Go en CLIs, agentes y servicios concurrentes. JavaScript/TypeScript en tooling de front, GitHub Actions y lambdas. El curso no te pide los tres: te pide uno con criterio."),
        ("p", "Python es el más recomendable para empezar: se lee casi como prosa, se interpreta al momento y hay librerías para SSH, HTTP, YAML y nubes."),
        ("callout", "Correctitud, diseño, estilo", "Un script de 30 líneas también se diseña. Nombres claros, funciones cortas, cero secretos en el código, y un README que explique cómo correrlo."),
        ("h2", "Conceptos que no son opcionales"),
        ("ul", [
            "Sintaxis, variables, tipos.",
            "Condicionales y bucles.",
            "Funciones y módulos.",
            "Listas, diccionarios y manejo de errores.",
            "Leer archivos, JSON/YAML y hacer una petición HTTP.",
        ]),
        ("h2", "Automatizar lo aburrido"),
        ("p", "El primer programa útil de DevOps no es un algoritmo elegante: es el que lista instancias, rota un log, valida un manifiesto o abre un ticket. Si ahorra trabajo humano repetible, ya es ingeniería."),
        ("code", "python", "import json, urllib.request\nurl = \"https://httpbin.org/get\"\nwith urllib.request.urlopen(url) as r:\n    data = json.load(r)\nprint(data[\"url\"])"),
    ],
    shorts=[
        ("Python", "Legible, enorme ecosistema, ideal para pegar APIs y archivos. Empieza aquí si no tienes preferencia."),
        ("Go", "Binario único, excelente concurrencia, muy usado en Kubernetes y CLIs. Curva más estricta, pago después."),
        ("JavaScript", "El lenguaje del navegador y de Node. Útil si ya vives en el ecosistema web o en GitHub Actions."),
        ("Prueba pequeña", "Si no puedes explicar un if, un for y una función, aún no automatices producción."),
    ],
    walkthrough=[
        "Instala el runtime (Python 3 recomendado).",
        "Escribe un script que imprima el día y liste archivos de un directorio.",
        "Añade un argumento de línea de comandos.",
        "Maneja un error (archivo que no existe) sin trazar un pánico ilegible.",
    ],
    pset_std=[
        ("Inventario", "Escribe un script que lea un JSON de servidores ficticios y imprima cuáles están 'down'."),
        ("Repetición", "Convierte un proceso manual de 5 pasos (renombrar archivos, por ejemplo) en un script."),
        ("Contrato", "Tu script debe aceptar --help y no crashear con entrada vacía."),
        ("Bitácora", "Registra lo que hace el script en un archivo app.log."),
    ],
    pset_hack=[
        ("Idempotencia", "Haz que correr el script dos veces no duplique efectos. Eso es DevOps de verdad."),
        ("Tests", "Si elegiste Go, sigue 'Learn Go with Tests'. Si Python, añade pytest a una función pura."),
    ],
    quiz=[
        ("¿Por qué un lenguaje en DevOps?",
         ["Para diseñar logos", "Para automatizar y versionar operaciones", "Para reemplazar Linux", "Para evitar Git"],
         1, "El código convierte ritos en sistemas."),
        ("¿Cuál es una buena primera lengua según este temario?",
         ["COBOL", "Python", "Malbolge", "Ensamblador del 6502"],
         1, "Python prioriza lectura y velocidad de llegada."),
        ("¿Qué debe vivir fuera del código?",
         ["Los nombres de funciones", "Los secretos y contraseñas", "Los bucles", "Los comentarios"],
         1, "Secretos en Git son incidentes esperando fecha."),
        ("Idempotencia significa:",
         ["Que el script es rápido", "Que repetirlo no cambia el resultado ya alcanzado", "Que usa hilos", "Que imprime JSON"],
         1, "La automatización segura se puede reejecutar."),
    ],
    feynman="Enseña qué es un script de automatización a una persona de negocio: entrada, proceso, salida, y por qué es mejor que un documento de 20 pasos.",
    flash=[
        ("¿Qué lenguajes se usan más en DevOps?", "Python, Go y JavaScript. Elige uno y llévalo a fluidez básica."),
        ("¿Qué hay que aprender primero de un lenguaje?", "Sintaxis, if/else, bucles, estructuras de datos y funciones. Luego archivos, errores y pruebas."),
        ("¿Para qué se usa un lenguaje en DevOps?", "Para automatizar tareas de desarrollo y operaciones, no para pulsar botones a mano."),
        ("¿Qué es la idempotencia?", "Ejecutar de nuevo no rompe ni duplica el estado deseado. Un script seguro se puede repetir."),
        ("¿Dónde deben vivir los secretos?", "En un gestor de secretos o en variables de entorno. Nunca en el repositorio."),
    ],
    resources=[
        ("Automate the Boring Stuff", "https://automatetheboringstuff.com/", "Python, gratis"),
        ("Python Crash Course extras", "https://ehmatthes.github.io/pcc/", "Gratis"),
        ("Eloquent JavaScript", "https://eloquentjavascript.net/", "Libro"),
        ("Go by Example", "https://gobyexample.com/", "Gratis"),
        ("Learn Go with Tests", "https://quii.gitbook.io/learn-go-with-tests", "Gratis"),
    ],
    rubric=("El script hace lo que promete el README.",
            "Funciones cortas, una responsabilidad, errores manejados.",
            "Nombres honestos, sin secretos, formato consistente."),
)

W(
    id="03",
    num=3,
    title="Linux y scripting",
    hours="10–14 h",
    skills=["Comandos de shell", "Sistema de archivos", "Red", "Virtualización", "POSIX"],
    goal="Sentirte en casa en un servidor Ubuntu. La terminal deja de ser un lugar hostil.",
    why="La mayoría de los servidores del mundo no tienen escritorio. Si no puedes moverte en Linux, DevOps se convierte en apuntar y rezar en una consola web.",
    lecture=[
        ("h2", "El sistema operativo como puente"),
        ("p", "Un sistema operativo media entre tú y el hardware: procesos, memoria, disco, red. En este oficio ese puente casi siempre se llama Linux. Ubuntu es un buen primer destino porque documenta mucho y perdona más."),
        ("p", "POSIX es el contrato de cómo se comportan shells, archivos y procesos en sistemas tipo Unix. Por eso un script bien escrito corre en Ubuntu, Debian y, con matices, en macOS."),
        ("h2", "El sistema de archivos no es una carpeta bonita"),
        ("p", "En Linux todo es un archivo: discos, sockets, pipes. /etc guarda configuración. /var logs y estado. /home a las personas. /proc y /sys son ventanas al kernel. Aprende a leer rutas antes de instalar el siguiente panel."),
        ("code", "bash", "pwd; ls -la\ncd /var/log && less syslog\nps aux | head\nss -tulpn\nchmod 640 secret.env\nsudo systemctl status ssh"),
        ("h2", "Scripting"),
        ("p", "Bash (o PowerShell en Windows) convierte una receta en un programa. Python y Go también sirven y a menudo escalan mejor. Empieza por Bash para la gramática del sistema; pasa a Python cuando el script crezca."),
        ("callout", "Práctica", "No memorices 200 comandos. Memoriza navegación, permisos, procesos, red básica, y cómo pedir ayuda: man, --help, tldr."),
    ],
    shorts=[
        ("Shell", "Un intérprete que lee tu texto y habla con el kernel. Bash es el más común en servidores."),
        ("Permisos", "rwx para usuario, grupo y otros. 644 y 755 no son magia: son bits."),
        ("Procesos", "PID, señales, systemd. Si no sabes matar un proceso, no sabes operar."),
        ("Virtualización", "Una máquina virtual simula hardware. Un contenedor comparte el kernel. No son lo mismo."),
    ],
    walkthrough=[
        "Instala Ubuntu en una VM (VirtualBox, UTM o cloud gratuito) o usa WSL2.",
        "Crea un usuario, una carpeta en /opt y un script que haga backup de un directorio.",
        "Usa chmod, ps, grep y journalctl una vez cada uno, con propósito.",
        "Escribe un Bash de 20 líneas con set -euo pipefail.",
    ],
    pset_std=[
        ("Casa nueva", "En una VM Ubuntu, crea usuarios, grupos y un directorio compartido con permisos correctos."),
        ("Mapa", "Dibuja (en texto) qué hay en /, /etc, /var, /home y /tmp y para qué sirve cada uno."),
        ("Salud", "Script que reporte disco, memoria y carga. Salida legible para humanos."),
        ("Cron", "Programa una tarea cada hora que rote o copie un log de ejemplo."),
    ],
    pset_hack=[
        ("POSIX estricto", "Escribe el script para que pase shellcheck y funcione en dash, no solo en bash."),
        ("Caja", "Levanta dos VMs y conéctalas por SSH con llaves, sin contraseña, con usuario no root."),
    ],
    quiz=[
        ("¿Por qué Linux en DevOps?",
         ["Porque es el único SO", "Porque la mayoría de servidores lo usan y se operan por CLI", "Porque no tiene red", "Porque reemplaza Git"],
         1, "La CLI es el idioma de los servidores."),
        ("POSIX es:",
         ["Un proveedor cloud", "Una familia de estándares Unix para APIs y shells", "Un firewall", "Un tipo de contenedor"],
         1, "El contrato que hace portables muchos scripts."),
        ("¿Qué hace chmod?",
         ["Cambia el dueño de la red", "Cambia permisos de un archivo", "Compila el kernel", "Crea un pod"],
         1, "Permisos: leer, escribir, ejecutar."),
        ("Una VM y un contenedor se diferencian porque:",
         ["La VM comparte el kernel del anfitrión", "El contenedor comparte el kernel; la VM emula o virtualiza hardware", "No hay diferencia", "El contenedor siempre es Windows"],
         1, "Esa diferencia explica aislamiento y arranque."),
    ],
    feynman="Describe un sistema operativo como si fuera el gerente de un edificio: quién entra, quién usa el elevador, quién escribe en la pizarra.",
    flash=[
        ("¿Qué distro Linux es amigable para empezar?", "Ubuntu. Luego da igual: la idea es POSIX, no la marca del escritorio."),
        ("¿Qué lenguajes de scripting son típicos en operaciones?", "Bash, PowerShell, Python y Go."),
        ("¿Qué es POSIX?", "Un estándar de interfaces Unix portables: comandos, archivos y procesos que se parecen entre sistemas."),
        ("¿Con qué comando listas procesos en Linux?", "ps. Para servicios del sistema, systemctl."),
        ("¿Dónde suele vivir la configuración del sistema?", "En /etc. Los logs, en /var/log."),
    ],
    resources=[
        ("Operating System Overview", "https://www.tutorialspoint.com/operating_system/os_overview.htm", "Gratis"),
        ("Shell Scripting Tutorial", "https://www.shellscript.sh/", "Gratis"),
        ("PowerShell tutorial", "https://www.guru99.com/powershell-tutorial.html", "Gratis"),
        ("Linux Commands Handbook", "https://www.freecodecamp.org/news/the-linux-commands-handbook/", "Gratis"),
        ("Getting started with Ubuntu", "https://itsfoss.com/getting-started-with-ubuntu/", "Gratis"),
    ],
    rubric=("El script corre en una VM limpia sin pasos secretos.",
            "Permisos mínimos; no todo es 777.",
            "El Bash tiene set -euo pipefail y nombres claros."),
)

W(
    id="04",
    num=4,
    title="Redes y seguridad",
    hours="10–14 h",
    skills=["Modelo OSI", "DNS", "HTTP", "SSH", "Herramientas de seguridad"],
    goal="Dejar de tratar la red como magia. Empaquetar, nombrar, cifrar y filtrar con intención.",
    why="Cada despliegue es una conversación entre máquinas. Si no entiendes DNS, puertos, TLS y firewalls, vas a depurar a ciegas cuando 'la app no carga'.",
    lecture=[
        ("h2", "Protocolo: un contrato de conversación"),
        ("p", "Un protocolo de red es un conjunto de reglas para transmitir datos entre dispositivos distintos. No importa que un lado sea Go y el otro Python: ambos hablan HTTP, DNS o SSH."),
        ("p", "El modelo OSI (7 capas) es un mapa mental, no un aparato. TCP/IP es lo que realmente corre. Tú, en la práctica, vives en: IP, TCP/UDP, TLS, HTTP y DNS."),
        ("h2", "Lo que debes poder explicar"),
        ("ul", [
            "Qué es una IP, una máscara y un puerto.",
            "La diferencia entre TCP (confiable) y UDP (rápido y olvida).",
            "Cómo un nombre (example.com) se convierte en IP (DNS).",
            "Qué hace SSH y por qué las llaves ganan a las contraseñas.",
            "Cómo un firewall decide qué entra y qué no.",
        ]),
        ("callout", "HTTP no es 'internet'", "HTTP es un protocolo de aplicación. Viaja sobre TCP (o QUIC). HTTPS es HTTP sobre TLS. Si mezclas estos términos en una incidente, el equipo pierde tiempo."),
        ("h2", "Seguridad como hábito"),
        ("p", "Principio de mínimo privilegio, superficies pequeñas, secretos fuera del código, y no exponer paneles a 0.0.0.0 sin autenticación. DevSecOps no empieza en la semana bonus: empieza cuando abres el primer puerto."),
    ],
    shorts=[
        ("DNS", "Jerarquía de nombres. El resolvers pregunta, los nameservers responden. TTL decide cuánto cacheas."),
        ("Puertos", "22 SSH, 53 DNS, 80 HTTP, 443 HTTPS. Un puerto cerrado es una puerta sin timbre."),
        ("SSH", "Shell remoto cifrado. Autenticación por llave. Túneles y port forwarding son superpoderes."),
        ("Firewall", "Reglas: de dónde, a dónde, qué protocolo. Deny by default es más sano que allow all."),
    ],
    walkthrough=[
        "Resuelve un dominio con dig o nslookup y lee la cadena de registros.",
        "Abre una conexión HTTP con curl -v y nombra cada fase.",
        "Genera un par de llaves SSH y entra a tu VM sin contraseña.",
        "Lista puertos abiertos con ss -tulpn.",
    ],
    pset_std=[
        ("Mapa OSI", "Escribe en una tabla un ejemplo real por cada capa que uses (HTTP, TLS, TCP, IP, Ethernet)."),
        ("Diagnóstico", "Simula 'no resuelve el dominio' vs 'resuelve pero el puerto 443 está cerrado'. Documenta cómo lo distingues."),
        ("Fortaleza mínima", "En tu VM, desactiva login SSH por contraseña y deja solo llaves."),
        ("HTTP visible", "Usa curl -v https://example.com y explica tres encabezados de la respuesta."),
    ],
    pset_hack=[
        ("TLS a mano", "Explica el apretón de manos TLS como una obra de teatro de 6 actos."),
        ("Mini firewall", "Escribe reglas ufw o iptables que solo permitan 22 y 443 desde tu IP."),
    ],
    quiz=[
        ("Un protocolo de red sirve para:",
         ["Enfriar el CPU", "Acordar cómo se transmiten datos entre dispositivos", "Dibujar el OSI en la pared", "Reemplazar Git"],
         1, "Es un contrato, no un producto."),
        ("DNS convierte:",
         ["JSON en YAML", "Nombres de dominio en direcciones IP (y más)", "HTTP en SSH", "Contenedores en VMs"],
         1, "El directorio telefónico de internet."),
        ("SSH debería autenticarse preferentemente con:",
         ["La contraseña root compartida", "Llaves públicas/privadas", "FTP", "Telnet"],
         1, "Las llaves no viajan y se revocan mejor."),
        ("¿Qué debes saber configurar además de DNS y OSI?",
         ["Firewalls, IPs y puertos", "Solo CSS", "Solo Jira", "Solo Figma"],
         0, "El temario pide red operativa, no teoría aislada."),
    ],
    feynman="Explícale a un adolescente cómo su teléfono encuentra google.com: nombre, DNS, IP, puerto 443, TLS, HTTP.",
    flash=[
        ("¿Qué es un protocolo de red?", "Un contrato de conversación: reglas para transmitir datos entre dispositivos distintos."),
        ("¿Qué capas de red debes poder explicar?", "IP, puertos, TCP y UDP, DNS, HTTP, SSH y el firewall."),
        ("¿Cuál es el puerto de HTTPS?", "443. HTTP en claro usa 80."),
        ("¿Qué herramienta usas para un shell remoto cifrado?", "SSH."),
        ("¿Qué es el modelo OSI?", "Un mapa de referencia de siete capas. En la práctica corre TCP/IP; OSI sirve para pensar."),
    ],
    resources=[
        ("OSI Model (Cloudflare)", "https://www.cloudflare.com/en-gb/learning/ddos/glossary/open-systems-interconnection-model-osi/", "Gratis"),
        ("How DNS works", "https://howdns.works/", "Gratis"),
        ("How HTTPS works", "https://howhttps.works/", "Gratis"),
        ("Computer Networking: A Top-Down Approach", "https://www.amazon.com/Computer-Networking-Top-Down-Approach-7th/dp/0133594149", "Libro"),
        ("Professor Messer Network+", "https://www.professormesser.com/network-plus/n10-008/n10-008-video/n10-008-training-course/", "Gratis"),
    ],
    rubric=("Puedes diagnosticar DNS vs puerto vs TLS.",
            "Las reglas de firewall son mínimas y justificadas.",
            "No hay secretos en capturas ni en el README."),
)

W(
    id="05",
    num=5,
    title="Administración de servidores",
    hours="8–12 h",
    skills=["Reverse proxy", "Servidor de caché", "Firewall", "Servidor web"],
    goal="Mantener un servidor rápido, vivo y aburrido — lo aburrido es un cumplido en operaciones.",
    why="El código no sirve si el proceso se cae, el disco se llena o el certificado caduca. Administrar servidores es el oficio de la confiabilidad cotidiana.",
    lecture=[
        ("h2", "Tres objetivos"),
        ("ul", [
            "Minimizar lentitud y caídas; maximizar confiabilidad.",
            "Construir entornos seguros.",
            "Escalar servidores y operaciones cuando la organización crece.",
        ]),
        ("h2", "Proxies, cachés y servidores web"),
        ("p", "Un proxy inverso (Nginx, Caddy, HAProxy, IIS ARR) recibe el tráfico del mundo y lo reparte a tus aplicaciones. Termina TLS, compacta, limita, enruta. Un proxy directo es el que usan los clientes para salir; no los confundas."),
        ("p", "Un servidor de caché guarda respuestas caras cerca de quien las pide. Un servidor web (Nginx, Apache, IIS) habla HTTP. En la práctica, Nginx suele ser las tres cosas: web, proxy inverso y, con un poco de configuración, caché."),
        ("callout", "Caja negra", "El usuario habla con un nombre y un puerto. Detrás puede haber 1 o 50 procesos. El proxy es la fachada. Si la fachada está mal, nada interior importa."),
        ("h2", "Operar"),
        ("p", "systemctl, logs, rotación, actualizaciones, backups, certificados, límites de ulimit, espacio en disco. Un servidor sin backup es un prototipo."),
    ],
    shorts=[
        ("Reverse proxy", "El mundo habla con Nginx; Nginx habla con tu app en 127.0.0.1:3000."),
        ("Caché", "No recalcules lo que no cambió. Ojo: invalidar caché es el problema difícil."),
        ("Firewall", "El servidor no necesita 65535 puertas abiertas. Abre las que el diseño pide."),
        ("Load balancing", "Varios backends, una fachada. Salud, reintentos, afinidad: detalles que evitan dramas."),
    ],
    walkthrough=[
        "Instala Nginx en Ubuntu.",
        "Sirve una página estática.",
        "Pon un proxy_pass a un proceso local (python -m http.server o similar).",
        "Fuerza HTTPS local con mkcert o un certificado autofirmado de laboratorio.",
    ],
    pset_std=[
        ("Fachada", "Nginx como reverse proxy a una app local. Documenta el server block."),
        ("Caché", "Activa caching de un recurso estático y demuestra con curl los encabezados."),
        ("Salud", "Explica cómo verías un 502 y qué mirarías primero (backend caído, socket, permisos)."),
        ("Endurecer", "Oculta la versión del servidor y desactiva listados de directorio."),
    ],
    pset_hack=[
        ("Dos backends", "Balancea dos procesos upstream y mata uno: el sitio debe sobrevivir."),
        ("Rate limit", "Limita peticiones por IP y demuestra el 429."),
    ],
    quiz=[
        ("El objetivo de administrar servidores NO es:",
         ["Reducir caídas", "Hacer el entorno seguro", "Escalar con la organización", "Memorizar todos los módulos de Apache"],
         3, "El objetivo es confiabilidad, seguridad y escala."),
        ("Un reverse proxy:",
         ["Es un cliente Tor", "Recibe tráfico externo y lo envía a servicios internos", "Solo cachea DNS", "Reemplaza Git"],
         1, "Fachada frente a los backends."),
        ("Nginx, Apache e IIS son ejemplos de:",
         ["Orquestadores", "Servidores web", "Bases de datos", "Hipervisores"],
         1, "Hablan HTTP, a menudo también hacen de proxy."),
        ("Un 502 Bad Gateway suele significar:",
         ["El HTML tiene un typo", "El proxy no pudo hablar con el backend", "El DNS es perfecto y nada más", "Falta un emoji"],
         1, "Mira el upstream primero."),
    ],
    feynman="Dibuja con palabras el camino de una petición desde el navegador hasta tu aplicación pasando por DNS, firewall, proxy y proceso.",
    flash=[
        ("¿Cuáles son las metas de administrar un servidor?", "Confiabilidad, seguridad y escala. Lo aburrido —que no se caiga— es un cumplido."),
        ("¿En qué se diferencia un reverse proxy de un forward proxy?", "El inverso es la fachada de tus servicios. El directo es la salida de los clientes hacia internet."),
        ("Nombra tres servidores web", "Nginx, Apache e IIS."),
        ("¿Qué es un caché en un servidor?", "Una copia temporal de respuestas caras para no calcularlas otra vez."),
        ("¿Qué códigos HTTP del proxy señalan un backend caído?", "502 o 504: el proxy está vivo; lo de atrás no responde a tiempo."),
    ],
    resources=[
        ("What is a reverse proxy?", "https://www.cloudflare.com/en-gb/learning/cdn/glossary/reverse-proxy/", "Gratis"),
        ("What is load balancing?", "https://www.cloudflare.com/en-gb/learning/performance/what-is-load-balancing/", "Gratis"),
        ("The Nginx Handbook", "https://www.freecodecamp.org/news/the-nginx-handbook/", "Gratis"),
    ],
    rubric=("La app responde a través del proxy, no a puerto crudo público.",
            "TLS, logs y un plan de backup existen aunque sean simples.",
            "La configuración está en Git, no solo en el servidor."),
)

W(
    id="06",
    num=6,
    title="Contenedores",
    hours="10–14 h",
    skills=["Correr contenedores", "Dockerfiles", "Red", "Docker Compose"],
    goal="Empaquetar una app para que corra igual en tu laptop y en un servidor.",
    why="El clásico 'en mi máquina funciona' se acaba cuando el artefacto incluye el runtime, las libs y la configuración mínima. Docker es, hoy, el empaque estándar.",
    lecture=[
        ("h2", "Qué es un contenedor"),
        ("p", "Un contenedor es una unidad estándar de software que empaca código y dependencias para que la aplicación corra igual de un entorno a otro. No es una VM: comparte el kernel del anfitrión y aísla procesos, sistemas de archivos y red."),
        ("p", "Una imagen es la receta inmutable. Un contenedor es la instancia en ejecución. El Dockerfile describe cómo se construye la imagen."),
        ("h2", "Lo que debes practicar"),
        ("ul", [
            "Correr contenedores, ver logs y entrar con exec.",
            "Escribir Dockerfiles pequeños y reproducibles.",
            "Volúmenes para persistir datos.",
            "Redes: cómo dos contenedores se hablan por nombre.",
            "Docker Compose para más de un contenedor.",
        ]),
        ("code", "dockerfile", "FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD [\"python\", \"app.py\"]"),
        ("callout", "Capa sobre capa", "Cada instrucción del Dockerfile es una capa. El orden importa: copia lo que cambia poco primero para no invalidar la caché."),
    ],
    shorts=[
        ("Imagen vs contenedor", "La imagen es la clase; el contenedor es el objeto. Puedes lanzar muchos de una."),
        ("Volumen", "Sin volumen, el disco del contenedor se esfuma al borrarlo. Las bases de datos necesitan memoria persistente."),
        ("Red bridge", "Compose crea una red. servicio-a puede resolver servicio-b por DNS interno."),
        ("Usuario no root", "Correr como root dentro del contenedor es un atajo que se paga en incidentes."),
    ],
    walkthrough=[
        "Instala Docker Engine o Docker Desktop.",
        "Corre nginx:alpine y ábrelo en un puerto local.",
        "Escribe un Dockerfile para un script de la semana 2.",
        "Crea un compose con app + un redis o postgres de laboratorio.",
    ],
    pset_std=[
        ("Empaque", "Dockeriza una app mínima. El contenedor debe arrancar con un solo comando."),
        ("Persistencia", "Añade un volumen y demuestra que los datos sobreviven a docker compose down / up."),
        ("Red", "Dos servicios en Compose; uno llama al otro por el nombre del servicio."),
        ("Higiene", ".dockerignore para no copiar .git ni secretos. Imagen < 200MB si puedes."),
    ],
    pset_hack=[
        ("Multi-stage", "Compila en una etapa y copia el binario/artefacto a una imagen slim."),
        ("No root", "USER no privilegiado y filesystem de solo lectura donde se pueda."),
    ],
    quiz=[
        ("Un contenedor empaca:",
         ["Solo el código fuente", "Código y dependencias para correr igual en distintos entornos", "Un hipervisor completo", "Únicamente el kernel"],
         1, "Esa es la definición del temario."),
        ("Docker es:",
         ["Un proveedor cloud", "La tecnología de contenedores más popular hoy", "Un lenguaje", "Un firewall"],
         1, "De facto el estándar de empaque."),
        ("Compose sirve para:",
         ["Orquestar clústeres de 500 nodos", "Definir y correr varios contenedores juntos", "Reemplazar Git", "Compilar el kernel"],
         1, "El laboratorio local de microservicios."),
        ("Una imagen es:",
         ["Un proceso en ejecución", "Un paquete inmutable y arrancable", "Una IP pública", "Un pull request"],
         1, "El contenedor es lo que corre."),
    ],
    feynman="Usa la analogía del tupper: la receta (Dockerfile), el tupper cerrado (imagen) y el tupper en la mesa (contenedor).",
    flash=[
        ("¿Qué es un contenedor?", "Una unidad que empaca código y dependencias para correr igual en tu laptop y en un servidor."),
        ("¿Cuál es la herramienta dominante de contenedores?", "Docker. La idea —aislar procesos con un sistema de archivos propio— es más grande que la marca."),
        ("¿Qué incluye una imagen de contenedor?", "Código, runtime, herramientas, librerías y ajustes. Es la receta; el contenedor es el plato."),
        ("¿Qué es Docker Compose?", "Varios contenedores definidos juntos en un YAML: red, volúmenes y orden de arranque."),
        ("¿Para qué sirve un volumen en Docker?", "Para persistir datos fuera del ciclo de vida del contenedor. Si el contenedor muere, el volumen sigue."),
    ],
    resources=[
        ("What are containers? (Google)", "https://cloud.google.com/learn/what-are-containers", "Gratis"),
        ("Container learning path", "https://iximiuz.com/en/posts/container-learning-path/", "Gratis"),
        ("Docker tutorial (YouTube)", "https://www.youtube.com/watch?v=3c-iBn73dDE", "Video"),
    ],
    rubric=("docker compose up --build funciona en una máquina limpia.",
            "Capas ordenadas, .dockerignore, un proceso por contenedor.",
            "Nombres de servicio claros, sin latest en producción si puedes fijar tags."),
)

W(
    id="07",
    num=7,
    title="Orquestación de contenedores",
    hours="12–18 h",
    skills=["Componentes", "CLI", "Namespaces", "Administrar", "Despliegue"],
    goal="Dejar de cuidar contenedores a mano. Kubernetes (o similar) declara el estado deseado y el clúster se esfuerza por cumplirlo.",
    why="Un contenedor es un proceso. Diez contenedores son un sistema. Cuando hay que reiniciar, escalar, sanar y exponer servicios, aparece el orquestador.",
    lecture=[
        ("h2", "Qué orquesta un orquestador"),
        ("p", "La orquestación automatiza despliegue, gestión, escala y red de contenedores. Sirve en cualquier entorno donde ya usas contenedores: el mismo manifiesto puede acercarte a desarrollo, staging y producción."),
        ("p", "Los microservicios en contenedores se vuelven manejables cuando el orquestador se ocupa del almacenamiento, la red y parte de la seguridad."),
        ("h2", "Kubernetes, sin mito"),
        ("p", "Un clúster tiene plano de control (API server, scheduler, etcd, controllers) y nodos de trabajo. Tú declaras: 'quiero 3 réplicas de esta imagen, con este puerto'. El control loop compara el mundo real con el declarado."),
        ("ul", [
            "Pod: el átomo. Uno o más contenedores que viajan juntos.",
            "Deployment: cómo se actualizan los pods.",
            "Service: un nombre estable frente a pods que nacen y mueren.",
            "Namespace: paredes de papel para equipos y ambientes.",
        ]),
        ("code", "bash", "kubectl get nodes\nkubectl create deployment web --image=nginx\nkubectl expose deployment web --port=80 --type=ClusterIP\nkubectl get pods -A"),
        ("callout", "No empieces en un EKS de 20 nodos", "Kind, k3d o minikube bastan para aprender el idioma. El cloud es la semana 11."),
    ],
    shorts=[
        ("Estado deseado", "Tú no 'arrancas' tanto como 'declaras'. El clúster reconcilia."),
        ("kubectl", "El CLI. Habla con el API server. Casi todo es un objeto YAML."),
        ("Namespace", "No es un firewall mágico, pero organiza y aplica cuotas y RBAC."),
        ("Rollout", "Un Deployment cambia pods poco a poco. Un crashloop es información, no un misterio."),
    ],
    walkthrough=[
        "Instala kubectl y un clúster local (kind/k3d/minikube).",
        "Despliega nginx y expónlo.",
        "Escala a 3 réplicas y observa los pods.",
        "Aplica un cambio de imagen y sigue el rollout.",
    ],
    pset_std=[
        ("Declarar", "Escribe un Deployment + Service en YAML. Nada de comandos imperativos en la entrega final."),
        ("Sanar", "Rompe la imagen a propósito y documenta los eventos del pod."),
        ("Namespace", "Crea un namespace dev y despliega ahí. kubectl -n dev get all."),
        ("Sonda", "Añade liveness o readiness y explica la diferencia en una frase cada una."),
    ],
    pset_hack=[
        ("Helm o Kustomize", "Parametriza el manifiesto. Un valor cambia el tag de imagen."),
        ("RBAC mínimo", "Una ServiceAccount que solo puede leer pods. Demuéstralo."),
    ],
    quiz=[
        ("La orquestación automatiza:",
         ["Solo el diseño gráfico", "Despliegue, gestión, escala y red de contenedores", "Únicamente DNS público", "La escritura de Python"],
         1, "Esa es la definición del temario."),
        ("Kubernetes te pide, sobre todo:",
         ["Hacer clic en 40 pantallas cada viernes", "Administrar el clúster y desplegar aplicaciones en él", "Reemplazar Linux", "Evitar YAML"],
         1, "Aprender a operar y a desplegar."),
        ("Un namespace sirve para:",
         ["Cifrar discos", "Aislar lógicamente objetos dentro del clúster", "Comprar dominios", "Hacer merge"],
         1, "Multitenancy ligera y orden."),
        ("El CLI principal es:",
         ["psql", "kubectl", "ffmpeg", "npm"],
         1, "Habla con el API server."),
    ],
    feynman="Compara un orquestador con un director de escena: tú escribes el libreto (YAML); el director se asegura de que siempre haya tres actores en el escenario.",
    flash=[
        ("¿Qué automatiza un orquestador de contenedores?", "Despliegue, reinicio, escala y red. Tú declaras el estado deseado; el clúster se esfuerza por cumplirlo."),
        ("¿Cuál es el orquestador dominante?", "Kubernetes."),
        ("¿Cuál es la unidad mínima de Kubernetes?", "El Pod: uno o más contenedores que comparten red y almacenamiento."),
        ("¿Cuál es la CLI de Kubernetes?", "kubectl. Con ella aplicas YAML, miras pods y lees logs."),
        ("¿Qué es un namespace en Kubernetes?", "Una partición lógica del clúster: nombres, cuotas y permisos separados."),
    ],
    resources=[
        ("Kubernetes in 4 hours (video)", "https://www.youtube.com/watch?v=s_o8dwzRIu4", "Video"),
        ("How Kubernetes came to be", "https://thenewstack.io/primer-how-kubernetes-came-to-be-what-it-is-and-why-you-should-care/", "Artículo"),
        ("KodeKloud Kubernetes path", "https://kodekloud.com/learning-path-kubernetes/", "Curso"),
    ],
    rubric=("El YAML aplica en un clúster limpio.",
            "Probes, recursos (CPU/RAM) y nombres con sentido.",
            "Sin kubectl apply de objetos sueltos sin etiqueta ni namespace."),
)

W(
    id="08",
    num=8,
    title="Infraestructura como código",
    hours="10–16 h",
    skills=["Aprovisionamiento", "Gestión de configuración", "Service mesh"],
    goal="Crear y destruir entornos con un comando, no con una checklist de la wiki.",
    why="IaC (YAML, JSON, HCL) convierte el centro de datos en un repositorio. Acelera y reduce el riesgo: el entorno 'dorado' se puede volver a nacer mañana.",
    lecture=[
        ("h2", "Dos oficios que se confunden"),
        ("p", "Aprovisionar es crear la materia: redes, VMs, buckets, clústeres. Terraform, Pulumi, CloudFormation, Bicep viven aquí. Configurar es dejar esa materia en el estado deseado: paquetes, usuarios, plantillas. Ansible, Chef, Puppet, y a veces cloud-init."),
        ("p", "Terraform es hoy el aprovisionador más portable entre nubes. El estado (state) es sagrado: describe qué existe de verdad. Sin backend remoto y locking, dos personas se pisan."),
        ("callout", "El entorno como oro", "Si tardas una semana en recrear staging, no tienes IaC: tienes arqueología. El estándar es nacer un ambiente bajo demanda."),
        ("h2", "Service mesh, en una idea"),
        ("p", "Cuando hay muchos servicios, el malla (Istio, Linkerd, Consul) mueve mTLS, reintentos y observabilidad al lado de cada pod. No lo necesitas el primer día. Sí debes saber que existe y qué problema ataca."),
        ("code", "hcl", "resource \"local_file\" \"bitacora\" {\n  filename = \"${path.module}/hola.txt\"\n  content  = \"Infraestructura como código\\n\"\n}"),
    ],
    shorts=[
        ("Declarativo", "Dices el qué, no el cómo. El motor calcula el diff."),
        ("Estado", "El archivo de state es el mapa. Cuídalo como una base de datos."),
        ("Módulos", "No copies 400 líneas. Empaqueta patrones reutilizables."),
        ("Drift", "Alguien cambió algo a mano en la consola. El próximo plan lo va a pelear."),
    ],
    walkthrough=[
        "Instala Terraform.",
        "Haz un laboratorio local (local_file o Docker provider) para entender init/plan/apply/destroy.",
        "Lee un plan antes de aplicar. Siempre.",
        "Destruye todo. El teardown es parte del oficio.",
    ],
    pset_std=[
        ("Plan primero", "Un módulo mínimo con terraform plan que cree un recurso inofensivo. Adjunta el plan en el README."),
        ("Idempotente", "Aplica dos veces. La segunda no debe recrear de más."),
        ("Variables", "Ningún valor mágico. variables.tf + terraform.tfvars de ejemplo (sin secretos)."),
        ("Destroy", "Documenta el destroy. Un entorno que no se puede apagar no es IaC, es una mascota."),
    ],
    pset_hack=[
        ("Ansible corto", "Un playbook que instale Nginx en tu VM y quede reejecutable."),
        ("Remote state", "Explica cómo guardar el state en S3/GitLab/Terraform Cloud y por qué el locking importa."),
    ],
    quiz=[
        ("IaC significa, sobre todo:",
         ["Dibujar servidores en Figma", "Definir infraestructura en código (YAML, JSON, HCL…)", "Apagar el firewall", "Evitar Git"],
         1, "Infraestructura versionada."),
        ("Terraform es popular para:",
         ["Edición de video", "Aprovisionar infraestructura", "Diseño de tipografías", "Compilar C"],
         1, "El temario lo señala como la herramienta más popular de provisioning."),
        ("Debes saber hacer:",
         ["Solo monitoreo", "Provisioning y configuration management", "Solo Scrum", "Solo HTML"],
         1, "Crear la materia y dejarla configurada."),
        ("El 'drift' es:",
         ["Un tipo de pod", "Cuando la realidad se aleja de lo declarado en código", "Un registro DNS", "Un load balancer"],
         1, "Cambios manuales contra el plan."),
    ],
    feynman="Explica por qué un servidor creado a mano es una mascota y uno creado con Terraform es ganado: se puede reemplazar sin funeral.",
    flash=[
        ("¿Qué es infraestructura como código?", "Definir servidores, redes y políticas en archivos versionados, no en clics de consola."),
        ("¿Cuál es la herramienta de provisioning más citada?", "Terraform. Describe el qué; el proveedor construye el cómo."),
        ("Nombra herramientas de configuration management", "Ansible, Chef y Puppet. Configuran máquinas ya existentes."),
        ("¿Qué es un service mesh?", "Una capa entre servicios para mTLS, tráfico y telemetría, sin reescribir cada app."),
        ("¿Qué diferencia hay entre terraform plan y apply?", "plan muestra el diff. apply muta el mundo. Nunca apply a ciegas."),
    ],
    resources=[
        ("Basic terms of IaC", "https://thenewstack.io/guis-cli-apis-learn-basic-terms-of-infrastructure-as-code/", "Artículo"),
        ("Comprehensive guide to Terraform", "https://blog.gruntwork.io/a-comprehensive-guide-to-terraform-b3d32832baca", "Guía"),
    ],
    rubric=("plan es legible; apply es reproducible.",
            "Módulos y variables; secretos fuera.",
            "Nombres consistentes; state no se sube al git público."),
)

W(
    id="09",
    num=9,
    title="CI/CD",
    hours="10–14 h",
    skills=["Montar el servidor", "Integración", "Herramientas de pipeline"],
    goal="Cada cambio en main se construye, se prueba y puede llegar a un entorno sin un ritual heroico.",
    why="CI/CD introduce automatización y monitoreo continuo desde la integración hasta el despliegue. Es la respuesta al miedo de juntar código el viernes.",
    lecture=[
        ("h2", "El tubo"),
        ("p", "Continuous Integration: cada commit (o PR) dispara una construcción y pruebas. Continuous Delivery: el artefacto queda listo para producción. Continuous Deployment: además, se publica solo si el tubo está verde."),
        ("p", "Un pipeline típico: obtener código → construir → analizar → probar → empaquetar → desplegar → verificar. Jenkins, GitHub Actions, GitLab CI, Circle, Azure DevOps: distinto YAML, misma idea."),
        ("h2", "Lo que debes montar"),
        ("ul", [
            "Un servidor o servicio de CI.",
            "Integración: el push dispara el tubo.",
            "Herramientas de build y empaquetado.",
        ]),
        ("code", "yaml", "name: ci\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: python -m compileall ."),
        ("callout", "El tubo es producto", "Si el pipeline es flaky, el equipo deja de creerlo. Un test inestable es un incidente cultural."),
    ],
    shorts=[
        ("Artefacto", "El binario, imagen o paquete que desplegarás. No redespliegues 'lo que había en la laptop'."),
        ("Gates", "No despliegues si fallan tests, linters o el escaneo de secretos."),
        ("Ambientes", "dev → staging → prod. Promueve el mismo artefacto; no reconstruyas en prod."),
        ("Secrets del CI", "El CI es un tesoro: tiene llaves de nube. Mínimo privilegio, rotación, logs sin secretos."),
    ],
    walkthrough=[
        "Elige GitHub Actions o GitLab CI (gratis y suficiente).",
        "Pipeline que corre en cada push: lint o tests mínimos.",
        "Guarda un artefacto (un .tar o una imagen en un registry de laboratorio).",
        "Añade un job de deploy a un entorno falso (una rama gh-pages o un directorio).",
    ],
    pset_std=[
        ("Verde", "Pipeline que falla si el código no compila o un test unitario cae."),
        ("PR check", "El merge a main queda bloqueado si el check está rojo (o documenta cómo se haría)."),
        ("Artefacto", "Publica un build (imagen Docker o zip) con un tag del commit."),
        ("README del tubo", "Explica cada job en lenguaje humano."),
    ],
    pset_hack=[
        ("Matriz", "Corre tests en dos versiones de runtime."),
        ("Deploy por ambientes", "manual approval para producción. El mismo artefacto que staging."),
    ],
    quiz=[
        ("CI/CD introduce, sobre todo:",
         ["Más reuniones", "Automatización en las etapas de desarrollo y entrega", "Un nuevo lenguaje", "Menos tests"],
         1, "Automatizar el camino a producción."),
        ("Un pipeline conecta:",
         ["Solo el diseño", "Integración, pruebas, entrega y despliegue", "Únicamente el firewall", "Solo el DNS"],
         1, "El temario habla de un tubo continuo."),
        ("Debes aprender a:",
         ["Montar el CI, integrar código y disparar pipelines, más herramientas de build", "Solo Jira", "Solo Figma", "Solo Excel"],
         0, "Servidor, integración, tools."),
        ("¿Por qué no reconstruir en producción?",
         ["Por moda", "Para desplegar el mismo artefacto que ya se probó", "Porque YAML lo prohíbe", "Porque Docker no puede"],
         1, "Reproducibilidad."),
    ],
    feynman="Cuenta la historia de un commit desde el teclado hasta un servidor, como si fuera un paquete en una fábrica con scanners en cada cinta.",
    flash=[
        ("¿Qué es integración continua (CI)?", "Integrar y probar en cada cambio, no al final de la semana."),
        ("¿Qué es entrega continua (CD)?", "Entregar o desplegar de forma continua cuando las pruebas pasan."),
        ("¿Qué es un pipeline?", "La cadena automatizada de esas etapas: clonar, probar, construir, publicar."),
        ("Nombra herramientas típicas de CI/CD", "Jenkins, GitHub Actions y GitLab CI."),
        ("¿Cuál es la regla de oro del artefacto?", "Construye una vez, despliega muchas. El binario de staging y el de producción son el mismo."),
    ],
    resources=[
        ("What is a CI/CD pipeline?", "https://semaphoreci.com/blog/cicd-pipeline", "Artículo"),
        ("Jenkins from zero to hero", "https://www.udemy.com/course/jenkins-from-zero-to-hero", "Curso"),
        ("GitLab CI tutorials", "https://docs.gitlab.com/ee/tutorials/", "Docs"),
    ],
    rubric=("El tubo corre en un clone limpio, no en tu laptop.",
            "Jobs cortos, cacheados con sentido, secretos en el almacén del CI.",
            "YAML legible; nombres de jobs que un extraño entiende."),
)

W(
    id="10",
    num=10,
    title="Monitoreo y observabilidad",
    hours="8–12 h",
    skills=["Infraestructura", "Aplicación", "Logs", "OpenTelemetry"],
    goal="Ver el sistema en tiempo real. Si duele, que duela con datos, no con intuición.",
    why="Monitorear es vigilar el ciclo completo: planear, desarrollar, integrar, desplegar y operar. En producción necesitas una vista viva de apps, servicios e infraestructura.",
    lecture=[
        ("h2", "De verde/rojo a las tres señales"),
        ("p", "Monitoreo clásico: ¿está vivo? Observabilidad: ¿puedo explicar por qué está lento sin SSH improvisado? Métricas, logs y trazas. Prometheus y Grafana son la pareja más citada para métricas y tableros. Los logs piden un almacén (Loki, ELK, cloud). Las trazas, un modelo como OpenTelemetry."),
        ("p", "SLIs, SLOs y error budgets convierten 'se siente lento' en una conversación de ingeniería. Alertar por síntoma (latencia, errores) suele ser mejor que alertar por cada CPU al 70%."),
        ("callout", "Si no está en un gráfico, no pasó", "El on-call futuro eres tú. Deja pistas: request_id, métricas RED (rate, errors, duration) y un dashboard que quepa en la cabeza."),
        ("h2", "Qué montar"),
        ("ul", [
            "Métricas de máquina y de aplicación.",
            "Logs con niveles y correlación.",
            "Un tablero. Una alerta que no sea ruido.",
        ]),
    ],
    shorts=[
        ("Prometheus", "Pull de métricas. PromQL. Alertmanager."),
        ("Grafana", "El lienzo. No es la fuente de verdad; es la vista."),
        ("Logs", "Demasiados son basura. Demasiado pocos son ceguera. Estructura (JSON) gana a prosa."),
        ("OpenTelemetry", "API + SDK + collectors para no casarte con un vendor de tracing."),
    ],
    walkthrough=[
        "Levanta Prometheus + Grafana en Compose (hay stacks de ejemplo).",
        "Expón una métrica de tu app o usa node_exporter en un host de lab.",
        "Dibuja un panel de CPU y de peticiones.",
        "Crea una alerta tonta (siempre falsa) y luego una útil.",
    ],
    pset_std=[
        ("Tablero", "Un dashboard con 4 paneles: vivo/muerto, CPU, memoria, errores."),
        ("Log útil", "Tu app escribe request_id. Muestras tres líneas correlacionadas."),
        ("Alerta", "Una regla con umbral y una descripción de qué hacer si dispara."),
        ("Runbook", "Media página: si la alerta X, mira Y, luego Z."),
    ],
    pset_hack=[
        ("RED", "Instrumenta rate, errors, duration de un endpoint."),
        ("OTel", "Una traza que cruce dos servicios locales."),
    ],
    quiz=[
        ("La observabilidad busca:",
         ["Más reuniones de status", "Una vista completa y en tiempo real del estado en producción", "Eliminar los logs", "Evitar Grafana"],
         1, "Ver para operar."),
        ("Pareja de herramientas más citada:",
         ["Photoshop y Excel", "Prometheus y Grafana", "Word y PowerPoint", "Figma y Notion"],
         1, "Métricas + visualización."),
        ("OpenTelemetry es:",
         ["Un cloud", "Un estándar/proyecto para telemetría (métricas, trazas, logs)", "Un firewall", "Un lenguaje"],
         1, "Para no atarte a un único vendedor."),
        ("Debes saber:",
         ["Solo diseñar slides", "Montar monitoreo y visualizar datos", "Solo escribir Java", "Solo DNS"],
         1, "El temario lo pide explícito."),
    ],
    feynman="Explica la diferencia entre 'la ambulancia llegó' (alerta) y 'el médico entiende al paciente' (observabilidad).",
    flash=[
        ("¿Qué es el monitoreo?", "Vigilar aplicaciones, servicios e infraestructura en tiempo real, con umbrales y alertas."),
        ("¿Qué es Prometheus?", "Un sistema de métricas por pull: raspa endpoints y guarda series temporales."),
        ("¿Qué es Grafana?", "Una herramienta para visualizar métricas, logs y trazas en tableros."),
        ("¿Cuáles son los tres pilares de la observabilidad?", "Métricas, logs y trazas. Juntos responden qué, dónde y por qué."),
        ("¿Qué es OpenTelemetry?", "Un estándar para emitir telemetría desde las apps, sin atarse a un solo vendedor."),
    ],
    resources=[
        ("What is observability?", "https://devopscube.com/what-is-observability/", "Artículo"),
        ("DevOps monitoring (Atlassian)", "https://www.atlassian.com/devops/devops-tools/devops-monitoring", "Artículo"),
        ("Basic vs advanced monitoring", "https://thenewstack.io/applying-basic-vs-advanced-monitoring-techniques/", "Artículo"),
    ],
    rubric=("Hay un tablero que un extraño entiende en 30 segundos.",
            "Las alertas tienen dueño y runbook.",
            "Los logs no contienen secretos."),
)

W(
    id="11",
    num=11,
    title="Un proveedor cloud",
    hours="12–20 h",
    skills=["IaaS, PaaS, SaaS", "Disponibilidad", "Administración", "Diseño e implementación"],
    goal="Pensar en APIs de infraestructura, no en un único servidor bajo el escritorio.",
    why="Los proveedores exponen APIs para crear recursos con fronteras de seguridad y de cobro. La nube corre en centros de datos, pero se siente como una plataforma. Saber provisionar, configurar y asegurar es el corazón del DevOps moderno — y de su complejidad.",
    lecture=[
        ("h2", "Elige uno y baja a tierra"),
        ("p", "AWS, Azure y Google Cloud dominan el mercado. Elige el que te abra más puertas en tu región o empleo objetivo. Los conceptos viajan: identidad, red, cómputo, almacenamiento, observabilidad, IAM."),
        ("p", "IaaS: alquilas VMs y discos. PaaS: te dan la plataforma (app service, Cloud Run, Elastic Beanstalk). SaaS: usas el software. DevOps vive sobre todo entre IaaS y PaaS."),
        ("h2", "Lo que debes practicar"),
        ("ul", [
            "Usuarios, roles, políticas. Nunca uses la cuenta root para el día a día.",
            "VPC/VNet, subnets públicas/privadas, NAT, security groups.",
            "Máquinas virtuales, discos, snapshots.",
            "Disponibilidad: zonas, regiones, backups, RPO/RTO en lenguaje humano.",
        ]),
        ("callout", "La nube no perdona el olvido", "Todo recurso tiene precio. Un laboratorio sin destroy es una factura. Etiqueta, presupuesto, alarma de costo."),
    ],
    shorts=[
        ("IAM", "Quién puede qué sobre cuál recurso. El error más caro es una llave de admin en un repo."),
        ("Región y zona", "La región es un geografía; la zona es un edificio (casi). Multi-AZ no es multi-región."),
        ("Security group", "Firewall de instancias. Egress también importa."),
        ("Cuenta y organización", "Separa prod de sandbox. El blast radius es un diseño, no un accidente."),
    ],
    walkthrough=[
        "Crea una cuenta de laboratorio (free tier) y activa MFA.",
        "Crea un usuario/rol de trabajo, no uses root.",
        "Levanta una VM mínima, entra por SSH, apágala.",
        "Mira la factura. Configura una alerta de costo.",
    ],
    pset_std=[
        ("Identidad", "Diagrama de cuentas/roles de tu lab. Root con MFA. Usuario de diario sin admin global."),
        ("Red", "Una VPC con subnet pública y otra privada. Explica el flujo."),
        ("Cómputo", "Una VM o un servicio PaaS sirviendo 'hola'. Se puede destruir con una guía de 5 pasos."),
        ("Costo", "Lista lo que dejaste encendido y cuánto estima el proveedor."),
    ],
    pset_hack=[
        ("IaC en la nube", "El laboratorio de la semana 8 ahora crea la VM/red en el proveedor real."),
        ("Alta disponibilidad", "Dos zonas, un balanceador. Mata una instancia y observa."),
    ],
    quiz=[
        ("Un cloud provider ofrece:",
         ["Solo laptops", "APIs que abstraen infraestructura con límites de seguridad y facturación", "Únicamente DNS doméstico", "Compiladores de C"],
         1, "Plataforma con cobro y frontera."),
        ("Los más citados en el temario:",
         ["AWS, Azure y Google Cloud", "Solo Heroku", "Solo Raspberry Pi", "Solo Dropbox"],
         0, "Los tres grandes."),
        ("Debes saber gestionar:",
         ["Solo CSS", "Usuarios, redes, servidores virtuales", "Solo Jira", "Solo Figma"],
         1, "IAM, red, cómputo."),
        ("IaaS vs PaaS:",
         ["IaaS es software de oficina", "IaaS alquila infraestructura; PaaS ofrece plataforma para correr apps", "No hay diferencia", "PaaS es un firewall"],
         1, "Quién parchea el SO marca la diferencia."),
    ],
    feynman="Explica la nube como un hotel: IaaS es alquilar la cocina, PaaS es pedir el menú, SaaS es sentarte a comer.",
    flash=[
        ("¿Cuáles son las nubes más comunes?", "AWS, Azure y Google Cloud. Aprende una de verdad; las demás se parecen."),
        ("¿Qué significan IaaS, PaaS y SaaS?", "Infraestructura, plataforma y software como servicio. Tú operas menos a medida que subes."),
        ("¿Qué debes practicar en un proveedor cloud?", "IAM, redes, máquinas virtuales y disponibilidad. Luego apaga el laboratorio."),
        ("¿Qué es una región cloud?", "Un conjunto de zonas en una geografía. Multi-zona aguanta un fallo de edificio; multi-región, un fallo de país."),
        ("¿Cuál es la regla de oro del laboratorio cloud?", "MFA, no uses la cuenta raíz a diario, y apaga lo que no estés usando."),
    ],
    resources=[
        ("AZ-900 (Microsoft)", "https://learn.microsoft.com/en-us/certifications/exams/az-900", "Certificación intro"),
        ("AWS Cloud Practitioner (Udemy)", "https://www.udemy.com/course/aws-certified-cloud-practitioner-new", "Curso"),
        ("A Cloud Guru AWS path", "https://acloudguru.com/learning-paths/aws-developer", "Path"),
    ],
    rubric=("El lab se puede crear y destruir con instrucciones claras.",
            "IAM mínimo, red justificada, sin 0.0.0.0/0 en SSH si puedes evitarlo.",
            "Etiquetas y alerta de costo."),
)

W(
    id="12",
    num=12,
    title="Prácticas de ingeniería de software",
    hours="6–10 h",
    skills=["Scrum", "Backlog", "Calidad integrada", "Comunicación", "Troubleshooting"],
    goal="Trabajar en un equipo ágil sin ser el cuello de botella ni el héroe solitario.",
    why="Vas a convivir con desarrollo en un mundo Scrum (o similar). Necesitas el ciclo de vida del software, las herramientas de ese ciclo, y cómo se prueba en automático para poder meterlo al pipeline.",
    lecture=[
        ("h2", "El ciclo y el ritual"),
        ("p", "SDLC: idea, análisis, diseño, implementación, prueba, despliegue, operación, mejora. Ágil no elimina el ciclo: lo hace corto y visible. Scrum propone backlog, sprint, daily, review, retro. Kanban visualiza el flujo. Elige el que el equipo ya usa y mejóralo con datos, no con dogmas."),
        ("p", "Calidad integrada (built-in quality): tests automáticos, revisiones, contratos de API, feature flags. El QA no es una casta al final; es una propiedad del tubo."),
        ("h2", "Comunicación y troubleshooting"),
        ("p", "Incidentes se narran: qué vimos, cuándo, qué hipótesis, qué se hizo, qué se aprendió. Blameless no es 'nadie es responsable': es 'el sistema permitió el error y el sistema se repara'."),
        ("callout", "Eres parte del producto", "Un pipeline inestable, un entorno que nadie puede recrear o un canal de Slack sin runbooks son deuda de ingeniería, no 'cosas de ops'."),
    ],
    shorts=[
        ("Backlog", "Lista ordenada de valor. Si todo es P0, nada es P0."),
        ("Definición de Terminado", "En producción, observable, con rollback. No 'en mi rama'."),
        ("Pirámide de tests", "Muchos unitarios, menos de integración, pocos E2E caros."),
        ("Postmortem", "Timeline, causa contribuyente, acciones. Sin villanos."),
    ],
    walkthrough=[
        "Lee una guía corta de Scrum y anota rituales vs principios.",
        "Toma un bug ficticio y escribe un reporte reproducible.",
        "Diseña una pirámide de tests para la app de la semana 6.",
        "Escribe un postmortem de un incidente inventado pero realista (certificado vencido).",
    ],
    pset_std=[
        ("Mapa SDLC", "Una página: dónde entra DevOps en cada fase."),
        ("Historia de usuario", "Escribe 3 historias con criterio de aceptación comprobable."),
        ("Calidad en el tubo", "Nombra qué test automático meterías en CI y por qué."),
        ("Incidente", "Postmortem de una caída de 20 minutos. Sin culpas, con acciones."),
    ],
    pset_hack=[
        ("Value stream", "Dibuja el camino de un ticket hasta prod y marca esperas. Propón recortar una."),
        ("Chaos narrado", "Diseña un game day de una hora para tu equipo imaginario."),
    ],
    quiz=[
        ("En este temario, Scrum es:",
         ["Un servidor web", "Un marco ágil de trabajo en equipo", "Un proveedor cloud", "Un tipo de pod"],
         1, "Rituales para entregar en ciclos cortos."),
        ("SDLC es:",
         ["Un firewall", "El ciclo de vida del desarrollo de software", "Un registry de Docker", "Un record DNS"],
         1, "De la idea a la operación."),
        ("La calidad integrada implica:",
         ["Probar solo al final, a mano", "Meter pruebas y revisión en el flujo diario y en CI/CD", "Eliminar QA", "No documentar"],
         1, "Built-in quality."),
        ("Un buen troubleshooting empieza por:",
         ["Reiniciar todo sin datos", "Reproducir, acotar, hipótesis, evidencia", "Culpar al último commit a ciegas", "Silenciar alertas"],
         1, "Método, no teatro."),
    ],
    feynman="Explica Scrum a alguien de finanzas: qué es un sprint, qué es un incremento, y por qué 'terminado' debe incluir 'en producción observable'.",
    flash=[
        ("¿Qué es Scrum?", "Un marco ágil: backlog, sprints cortos, inspección y adaptación. No es un ritual vacío de reuniones."),
        ("¿Qué es el SDLC?", "Las fases del ciclo de vida del software: idea, diseño, construcción, prueba, operación y retiro."),
        ("¿Qué significa built-in quality?", "La calidad no se inspecciona al final: se construye en cada paso, con pruebas y revisión."),
        ("¿Dónde viven las pruebas automáticas en DevOps?", "En el pipeline de CI. Si no corren solas, no existen el sábado a las once."),
        ("¿Para qué sirve un postmortem?", "Para aprender de un incidente con línea de tiempo y acciones, sin cazar brujas."),
    ],
    resources=[
        ("Ways to learn Scrum", "https://www.scrum.org/resources/ways-learn-about-scrum", "Gratis"),
        ("SDLC tutorial", "https://www.guru99.com/software-development-life-cycle-tutorial.html", "Gratis"),
        ("Automation testing for beginners", "https://blog.testproject.io/2020/03/26/automation-testing-for-beginners-ultimate-guide/", "Guía"),
    ],
    rubric=("Las historias se pueden probar.",
            "El postmortem tiene timeline y acciones.",
            "El lenguaje es preciso, sin jerga de adorno."),
)

W(
    id="13",
    num=13,
    title="Bonus: DevSecOps",
    hours="6–10 h",
    skills=["SAST/DAST", "Secretos", "Políticas", "Supply chain"],
    goal="Meter la seguridad en el tubo, no al final como un veto sorpresa.",
    why="El bonus del roadmap original: integrar seguridad en DevOps. Automatizar análisis de código y de apps en ejecución, cuidar secretos y fijar políticas.",
    lecture=[
        ("h2", "Izquierda, pero con juicio"),
        ("p", "Shift-left no significa que desarrollo se vuelva un equipo de pentesting. Significa: secretos fuera, dependencias parcheadas, SAST en el PR, DAST en staging, imágenes firmadas, políticas (OPA, Kyverno) en el clúster."),
        ("ul", [
            "SAST: mira el código sin ejecutarlo.",
            "DAST: ataca la app corriendo.",
            "SCA: las librerías de terceros también son tu código.",
            "Secrets management: rotación, no un .env eterno.",
        ]),
        ("callout", "El tubo como aduana", "Un hallazgo crítico detiene el merge. Uno medio abre un ticket. Si todo es bloqueo, el equipo apaga el scanner."),
    ],
    shorts=[
        ("Secretos", "Vault, SOPS, secrets del CI, managers de la nube. Nunca el chat."),
        ("SBOM", "Lista de ingredientes del artefacto. Útil cuando sale el próximo CVE."),
        ("Imagen", "Escanea (Trivy, Grype). No corras latest ciego."),
        ("Política", "Como código. El clúster rechaza pods privilegiados."),
    ],
    walkthrough=[
        "Añade un scan de secretos (gitleaks o similar) al pipeline.",
        "Escanea tu imagen Docker.",
        "Mueve un secreto de un archivo a una variable de entorno.",
        "Lee un informe SAST aunque sea de un linter de seguridad básico.",
    ],
    pset_std=[
        ("Secretos", "Demuestra un repo limpio: pre-commit o pipeline que falle si hay AWS keys de ejemplo."),
        ("CVE", "Escanea la imagen y documenta un hallazgo: ¿lo aceptas, lo parchas o lo mitigas?"),
        ("Amenaza corta", "Tres amenazas de tu app de lab y un control para cada una."),
        ("Política", "Escribe en prosa la política: no root, no :latest, no puertos abiertos de más."),
    ],
    pset_hack=[
        ("Firma", "Firma una imagen (cosign) y verifica antes de desplegar."),
        ("Policy as code", "Una regla de Kyverno/OPA que rechace privileged: true."),
    ],
    quiz=[
        ("DevSecOps busca:",
         ["Dejar la seguridad para el último martes del año", "Integrar seguridad en el flujo DevOps", "Eliminar firewalls", "Prohibir la nube"],
         1, "Seguridad continua."),
        ("SAST es:",
         ["Atacar la app en ejecución", "Analizar código en reposo", "Un load balancer", "Un ritual Scrum"],
         1, "Static Application Security Testing."),
        ("Un secreto en Git es:",
         ["Buena documentación", "Un incidente en potencia, aunque lo borres después", "Un tipo de pod", "Un SLO"],
         1, "El historial lo conserva."),
        ("Shift-left bien hecho:",
         ["Bloquea todo y detiene al equipo", "Automatiza controles tempranos con umbrales razonables", "Elimina producción", "Sustituye a IAM"],
         1, "Juicio + automatización."),
    ],
    feynman="Explícale a un product manager por qué un scanner en el PR es más barato que un titular de filtración.",
    flash=[
        ("¿Qué es DevSecOps?", "Integrar la seguridad en el ciclo DevOps, no dejarla para un veto el último martes del año."),
        ("¿En qué se diferencia SAST de DAST?", "SAST analiza el código en reposo. DAST ataca la aplicación mientras corre."),
        ("¿Qué es SCA?", "Software Composition Analysis: el riesgo que entra por las dependencias."),
        ("¿Qué es un SBOM?", "La lista de ingredientes del artefacto: qué librerías, qué versiones, qué licencias."),
        ("¿Cuál es la regla de los secretos?", "Nunca en Git. Siempre rotables. Si se filtró, se revoca; borrar el commit no basta."),
    ],
    resources=[
        ("Repo original del roadmap", "https://github.com/milanm/DevOps-Roadmap", "Fuente"),
        ("OWASP Top 10", "https://owasp.org/www-project-top-ten/", "Gratis"),
        ("How HTTPS works", "https://howhttps.works/", "Gratis"),
    ],
    rubric=("El pipeline detecta al menos una clase de problema de seguridad.",
            "Hay política escrita y un lugar donde se aplica.",
            "Los secretos de lab no son reales; los reales no están en el repo."),
)

BOOKS = [
    ("The DevOps Handbook", "Kim, Humble, Debois, Willis"),
    ("Accelerate", "Forsgren, Humble, Kim"),
    ("The Phoenix Project", "Kim, Behr, Spafford"),
    ("Site Reliability Engineering", "Google / Beyer et al."),
    ("Continuous Delivery", "Humble, Farley"),
    ("Team Topologies", "Skelton, Pais"),
]

TOOLS = [
    ("Seguimiento del trabajo", ["Asana", "Jira"]),
    ("Control de versiones", ["Git", "GitHub", "GitLab"]),
    ("CI/CD", ["Jenkins", "GitHub Actions", "GitLab CI"]),
    ("Análisis de código", ["SonarQube"]),
    ("Artefactos", ["Artifactory", "Registro de imágenes"]),
    ("Infraestructura como código", ["Terraform", "Ansible", "Puppet", "Chef"]),
    ("Contenedores y orquestación", ["Docker", "Kubernetes", "Helm"]),
    ("Observabilidad", ["Prometheus", "Grafana", "OpenTelemetry"]),
    ("Nube", ["AWS", "Azure", "Google Cloud"]),
    ("Seguridad", ["SAST", "DAST", "Vault", "Trivy"]),
]

PEDAGOGY = [
    ("Piso bajo, techo alto", "Como CS50: se entra sin experiencia y se sale con rigor. Hay vía estándar y vía hacker."),
    ("Conferencia → cortos → práctica", "Primero la idea, luego piezas de 2 minutos, luego un problem set. No al revés."),
    ("Recuerdo activo", "Cerrar las notas y responder. Releer no es aprender; recuperarlo de la memoria sí."),
    ("Repetición espaciada", "En cada sesión, las que fallas vuelven ya. Al cerrar el navegador, el mazo se reinicia: es para practicar, no para coleccionar rachas."),
    ("Feynman", "Si no puedes explicarlo en voz simple, aún no lo tienes. El recuadro de cada semana existe para eso."),
    ("Correctitud, diseño, estilo", "Tres ejes, como en CS50. Que funcione no basta; que se pueda operar y leer también."),
]

# Práctica por semana: drills de conferencia (título = h2), cortos, recorrido, pistas del pset y refuerzo final.
DRILLS = {
    "01": {
        "lecture": [
            ("La caja negra", "En una frase: ¿qué problema resuelve Git que una carpeta «final-final-v3.zip» no resuelve?", "Un commit es una foto del proyecto con autor, mensaje y padre. El zip no sabe de dónde vino ni cómo volver atrás sin romper a los demás."),
            ("Comandos que sí vas a usar", "Escribe, en orden, los comandos para clonar un repo, cambiar un archivo y publicar el commit.", "git clone → git status → git add → git commit -m \"…\" → git push. Si es rama nueva: git switch -c nombre antes del push."),
            ("Ramas, fusión y pull requests", "¿Cuándo harías merge y cuándo rebase? Una frase para cada uno.", "Merge conserva las dos historias. Rebase reescribe la tuya encima de main. Nunca hagas rebase de una rama que ya comparte el equipo."),
        ],
        "shorts": ("Elige un corto y explícalo sin mirar el texto.", "Di en voz alta: commit, rama, pull request o conflicto. Si te trabas, vuelve a leer solo ese corto."),
        "walk": ("Anota el primer comando que te falló y el mensaje de error.", "Lee el error de abajo hacia arriba. «command not found» = instala Git y abre otra terminal. «permission denied» no se arregla siempre con sudo."),
        "std": [
            "git init bitacora; crea README.md; tres commits pequeños con git add y git commit -m. git log --oneline debe mostrar tres líneas.",
            "git switch -c experimento; edita; commit; git switch main; git merge experimento. Luego git log --oneline --graph.",
            "Crea el repo vacío en GitHub/GitLab, git remote add origin URL, git push -u origin main. El PR puede ser de una rama tonta hacia main.",
            "Crea .gitignore con esas líneas, git add .gitignore, commit. git status debe ignorar un .env de prueba.",
        ],
        "hack": [
            "Clona un repo pequeño, git blame archivo, o git bisect start y sigue las pistas de man git-bisect.",
            "revert crea un commit nuevo que deshace; reset mueve el puntero (peligroso en main). Escríbelo en el README del lab.",
        ],
        "encore": ("Bitácora de un día", "Repo `hoy` con tres commits: mañana, tarde y un arreglo. Mensajes en presente: «añade», «arregla».", "git init hoy && cd hoy. Crea archivos de una línea. git add + git commit tres veces. git log --oneline."),
    },
    "02": {
        "lecture": [
            ("Elige uno. Domínalo.", "Elige Python, Go o JavaScript y escribe por qué te sirve en operaciones, no en abstracto.", "Python: scripts y pegamento. Go: binarios y CLIs. JS: automatizar lo que ya vive en Node. Uno basta para empezar."),
            ("Conceptos que no son opcionales", "Escribe un pseudo-código de 8 líneas: leer un archivo, filtrar líneas, imprimir. Sin copiar un tutorial.", "Abre, recorre, if, print. Si no recuerdas la sintaxis, anota «abrir archivo» y «filtrar» en español: ya es un algoritmo."),
            ("Automatizar lo aburrido", "Nombra una tarea de 5 clics que harás más de una vez esta semana y descríbela como entrada → proceso → salida.", "Entrada: lista o carpeta. Proceso: transformar. Salida: archivo o mensaje. Los secretos no van en el script."),
        ],
        "shorts": ("Explica idempotencia con un ejemplo casero (no de servidores).", "Encender la luz dos veces no funde la bombilla. Un script que crea una carpeta no debe fallar si ya existe."),
        "walk": ("Pega aquí la primera función que te compiló o ejecutó.", "Si el lenguaje «no se encuentra»: instálalo y cierra la terminal. Empieza con print/fmt.Println, no con un framework."),
        "std": [
            "Un JSON con 3 servidores y un campo status. Recorre e imprime los down. En Python: json.load + un for.",
            "Renombrar, copiar o listar. 15 líneas cuentan. No uses la GUI para el paso repetido.",
            "argparse o flag. Si argv está vacío, imprime uso y sal con código 0 o 1 consciente, no con traceback.",
            "open('app.log','a') o equivalente. Una línea por acción: hora y qué hizo.",
        ],
        "hack": [
            "Si creas un archivo, comprueba que no exista o ábrelo en modo que no duplique. mkdir -p es el espíritu.",
            "Una función pura + un assert o pytest. En Go, TestXxx en el mismo paquete.",
        ],
        "encore": ("Script de bolsillo", "Un script `hoy.py`/`hoy.go`/`hoy.js` que reciba un nombre y salude, y que `--help` exista.", "Empieza por print. Luego un if de argumentos. El help puede ser un string. No hace falta un parser elegante."),
    },
    "03": {
        "lecture": [
            ("El sistema operativo como puente", "¿Qué es un proceso, en una frase, y cómo lo listas?", "Un programa en ejecución. ps aux o ps -ef. systemctl para servicios, no para un script suelto."),
            ("El sistema de archivos no es una carpeta bonita", "¿Qué pondrías en /etc, /var y /home? Una línea cada uno.", "/etc configuración. /var datos que cambian (logs). /home personas. No mezcles binarios de sistema en /home."),
            ("Scripting", "Escribe un one-liner mental: «si el disco pasa del 80%, avísame».", "df -h, awk o un if en bash. Empieza por df y un umbral; el correo o el echo pueden esperar."),
        ],
        "shorts": ("Di en voz alta qué es POSIX y por qué te importa en un script.", "Si escribes para bash «puro» con [[ ]] y arrays, en dash se rompe. POSIX es el subconjunto portable."),
        "walk": ("Anota un comando de hoy (ls, chmod, journalctl…) y qué aprendiste del man.", "man <comando>. La sección EXAMPLES al final suele ser oro. Si no hay man, tldr o --help."),
        "std": [
            "adduser/usermod y chmod 2775 o similar en el directorio compartido. Documenta ls -ld.",
            "Un bloque de texto: ruta, para qué, quién escribe. No hace falta un diagrama bonito.",
            "free -h, df -h, uptime. Un script que los imprime con etiquetas ya cuenta.",
            "crontab -e: 0 * * * * y un script que copia un archivo. crontab -l como evidencia.",
        ],
        "hack": [
            "apt install shellcheck; shellcheck script.sh. Evita bashismos si pides dash.",
            "ssh-keygen, copiar .pub a authorized_keys, PermitRootLogin no. Prueba ssh user@host.",
        ],
        "encore": ("Primera casa", "En tu máquina o una VM: crea `~/lab`, un script `salud.sh` ejecutable que imprima fecha y df -h.", "chmod +x salud.sh. La primera línea: #!/bin/sh. Ejecuta ./salud.sh, no sh si ya es ejecutable."),
    },
    "04": {
        "lecture": [
            ("Protocolo: un contrato de conversación", "Inventa un protocolo de 4 reglas para pedir café por mensaje. Luego nombra el análogo en HTTP.", "Verbo (GET/POST), recurso (/cafe), encabezados (leche, tamaño), código de respuesta (200, 404, 503)."),
            ("Lo que debes poder explicar", "Alguien dice «no carga la web». Escribe las tres primeras preguntas que harías.", "¿Resuelve DNS? ¿El puerto 443 responde? ¿TLS/certificado? ping no basta; curl -v y dig sí."),
            ("Seguridad como hábito", "Nombra dos hábitos de SSH que no cuestan dinero.", "Llaves, no contraseñas. No root remoto. Actualizar. Fail2ban si quieres, pero las llaves primero."),
        ],
        "shorts": ("Explica DNS a alguien que cree que «internet es Google».", "DNS traduce nombres a números. Si falla el traductor, la web «no existe» aunque el servidor esté vivo."),
        "walk": ("Pega tres líneas de `curl -v` que te hayan servido y qué significan.", "Busca HTTP/1.1 o HTTP/2, el código (200/301/403) y server:. El certificado aparece en las líneas SSL."),
        "std": [
            "Capa 7 HTTP, 6 TLS, 4 TCP, 3 IP, 2 Ethernet. Una fila por capa con un ejemplo que uses de verdad.",
            "No resuelve: dig/nslookup falla. Resuelve pero 443 cerrado: nc/curl timeout tras tener IP. Anótalo.",
            "sshd_config: PasswordAuthentication no. Recarga sshd. Ten otra sesión abierta antes de cortar.",
            "curl -v: date, server, cache-control o strict-transport-security. Explícalos en español.",
        ],
        "hack": [
            "Cliente saluda, servidor certificado, claves, cifrado, datos, cierre. 6 frases numeradas.",
            "ufw allow from TU_IP to any port 22 y 443. ufw enable con cuidado: no te bloquees.",
        ],
        "encore": ("Diagnóstico de café", "Escribe un runbook de 8 líneas: «la web no carga». Orden: DNS, puerto, TLS, app.", "1. ping o dig. 2. curl -I. 3. ¿certificado?. 4. logs. No empieces por reinstalar Nginx."),
    },
    "05": {
        "lecture": [
            ("Tres objetivos", "Para tu lab, define «confiabilidad» en una métrica tonta pero medible.", "«Responde 200 en /salud 99 de cada 100 curl». Mejor una métrica chica que «que no se caiga»."),
            ("Proxies, cachés y servidores web", "Dibuja en texto: cliente → proxy → app. ¿Dónde vive el TLS?", "Casi siempre en el proxy (Nginx). La app habla HTTP en localhost. 502 = el proxy no logra hablar con la app."),
            ("Operar", "Si ves 502, ¿qué miras primero: el proxy o la app?", "El proxy está vivo (si ves 502). Mira si el upstream escucha, el socket, los permisos y el error.log."),
        ],
        "shorts": ("Reverse vs forward proxy, con una analogía de edificio.", "Reverse: recepción del edificio (tus servicios). Forward: el portero que sale a la calle por ti (la oficina)."),
        "walk": ("Anota el server block mínimo que harías copiar/pegar y qué línea no entiendes.", "listen 80; server_name; location / { proxy_pass http://127.0.0.1:PUERTO; }. El trailing slash importa."),
        "std": [
            "Un server { listen 80; location / { proxy_pass http://127.0.0.1:3000; } }. nginx -t y recarga.",
            "proxy_cache o expires para un CSS. curl -I dos veces: busca Age o X-Cache-Status.",
            "error.log del proxy + ¿escucha el puerto? ss -lptn. 502 no es «reinicia el mundo».",
            "server_tokens off; autoindex off. nginx -t. Evidencia: curl -I ya no grita la versión.",
        ],
        "hack": [
            "upstream { server 127.0.0.1:3001; server 127.0.0.1:3002; } Mata uno; curl sigue 200.",
            "limit_req_zone. Demuéstralo con un bucle de curl hasta 429.",
        ],
        "encore": ("Una fachada", "Sirve un archivo estático con Nginx en el 8080 de tu máquina (o un contenedor). curl localhost:8080 debe 200.", "Un server { listen 8080; root /ruta; index index.html; }. nginx -t. Si el puerto está ocupado, cambia 8080."),
    },
    "06": {
        "lecture": [
            ("Qué es un contenedor", "¿En qué se parece un contenedor a un proceso y en qué no a una VM?", "Comparte el kernel (como un proceso). Aísla archivos y red (como una VM chica). No arranca otro sistema operativo completo."),
            ("Lo que debes practicar", "Escribe un Dockerfile de 6 líneas para una app que solo imprime hola.", "FROM, WORKDIR, COPY, RUN si hace falta, USER no root si puedes, CMD. .dockerignore con .git."),
        ],
        "shorts": ("Imagen vs contenedor, en una analogía de cocina.", "Imagen = receta congelada. Contenedor = el plato sirviéndose. Varios platos de la misma receta."),
        "walk": ("Pega el error de tu primer docker build y qué línea del Dockerfile lo causó.", "«file not found» suele ser COPY + contexto. El Dockerfile ve el directorio desde donde corres build, no magia."),
        "std": [
            "Dockerfile + docker compose up --build. Un puerto publicado. README con el comando único.",
            "volumes: - data:/ruta. Escribe un archivo dentro, down, up, el archivo sigue.",
            "services: api y web. web hace GET a http://api:puerto. El nombre del servicio es el DNS interno.",
            ".dockerignore: .git, .env, node_modules. docker images; el tamaño importa.",
        ],
        "hack": [
            "FROM golang AS build … y FROM scratch o distroless con el binario. Dos FROM.",
            "USER 65532 o un user creado. read_only: true en compose si la app lo aguanta.",
        ],
        "encore": ("Hola en una caja", "Contenedor que responde «hola» en un puerto. Un comando para arrancar, uno para parar.", "Si no tienes app: nginx:alpine y un index.html copiado. docker run --rm -p 8080:80 imagen."),
    },
    "07": {
        "lecture": [
            ("Qué orquesta un orquestador", "¿Qué deja de hacer una persona cuando hay Kubernetes (o similar)?", "Reiniciar a mano, decidir en qué máquina, abrir puertos a dedo. Tú declaras replicas: 2; el clúster se esfuerza."),
            ("Kubernetes, sin mito", "¿Qué es un Pod, en una analogía, y por qué casi nunca corres un contenedor «suelto» en K8s?", "El Pod es la caja donde viven los contenedores que se necesitan juntos. K8s programa Pods, no Docker run sueltos."),
        ],
        "shorts": ("kubectl en una frase: ¿qué le pides al clúster?", "«Aplica este YAML» y «enséñame el estado». get, describe, logs, apply. Poco más para empezar."),
        "walk": ("Anota un apply que falló y el campo YAML que lo rompió.", "indentación. apiVersion/kind. image: que no existe. kubectl describe pod es más útil que el apply rojo."),
        "std": [
            "kind: Deployment y Service. kubectl apply -f. Nada de kubectl run en la entrega.",
            "Pon un tag de imagen inventado, apply, kubectl describe pod / get events.",
            "kubectl create ns dev; metadata.namespace: dev. kubectl -n dev get all.",
            "liveness = «¿sigo vivo?»; readiness = «¿ya puedo recibir tráfico?». Una frase cada una en el README.",
        ],
        "hack": [
            "values.yaml con image.tag. helm upgrade o kustomize edit set image.",
            "Role + RoleBinding + ServiceAccount. kubectl auth can-i get pods --as=system:serviceaccount:dev:sa",
        ],
        "encore": ("Declarar, no pulsar", "Un YAML de Deployment con 2 réplicas de nginx. Aplícalo en kind, k3d o minikube.", "Si no tienes clúster: instala kind. kind create cluster. kubectl apply -f. kubectl get pods."),
    },
    "08": {
        "lecture": [
            ("Dos oficios que se confunden", "¿Qué hace Terraform que Ansible no hace (y al revés), en una frase cada uno?", "Terraform crea/destruye la nube (provisioning). Ansible configura lo que ya existe (configuration management). Se pueden usar juntos."),
            ("Service mesh, en una idea", "¿Qué problema de mTLS/tráfico resolvería un mesh que no quieres meter en cada app?", "Certificados entre servicios, reintentos, observabilidad. El sidecar habla; tu código sigue siendo HTTP."),
        ],
        "shorts": ("plan vs apply, como si firmaras un contrato.", "plan = lees el contrato. apply = firmas. Nunca firmes sin leer. terraform plan -out y luego apply ese archivo."),
        "walk": ("Escribe el recurso más pequeño que te atreverías a crear y cómo lo destruirías.", "Un local_file o un droplet de 5 dólares. terraform destroy es parte de la demo, no un apéndice."),
        "std": [
            "Un .tf mínimo, terraform init, terraform plan. Pega el plan (sin secretos) en el README.",
            "terraform apply dos veces. La segunda: 0 to add, 0 to destroy.",
            "variable \"nombre\" {}. tfvars de ejemplo. Cero IPs o passwords en el .tf.",
            "terraform destroy y captura la salida. Si da miedo, el diseño es de mascota, no de ganado.",
        ],
        "hack": [
            "hosts.ini + playbook.yml con apt: name=nginx state=present. ansible-playbook dos veces.",
            "El state es el mapa del mundo. Si dos personas apply a la vez, se pisan. Locking = un candado en el mapa.",
        ],
        "encore": ("Plan de juguete", "Un terraform que cree un archivo local. plan, apply, destroy. Tres capturas en el README.", "resource \"local_file\" \"hola\" { content = \"hola\\n\" filename = \"${path.module}/hola.txt\" } terraform init && plan && apply."),
    },
    "09": {
        "lecture": [
            ("El tubo", "Dibuja CI y CD en dos cajas. ¿Qué cruza de una a la otra?", "CI: test + build. CD: ese mismo artefacto a un entorno. El zip o la imagen es el puente. No se recompila «a mano» en prod."),
            ("Lo que debes montar", "Nombra tres jobs de un pipeline mínimo y qué los pone rojos.", "lint/test, build, publicar. Rojo: test fallido, no compila, no hay artefacto. Un job que «siempre verde» no sirve."),
        ],
        "shorts": ("«Construye una vez, despliega muchas»: ¿por qué duele reconstruir en producción?", "El binario de staging y el de prod deben ser el mismo. Si recompilas, ya no sabes qué probaste."),
        "walk": ("Pega el YAML de un job (aunque sea de ejemplo) y marca con un comentario qué no entiendes.", "on: push. jobs: pasos. runs-on. Si falla «permission denied» en GitHub Actions, mira permissions: contents."),
        "std": [
            "Un workflow o .gitlab-ci.yml con un test que puedas romper a propósito. El rojo debe ser visible.",
            "Branch protection o una nota: «así se bloquearía». Settings → Branches si usas GitHub.",
            "docker build -t org/app:$GITHUB_SHA o artefactos. El tag es el commit, no latest.",
            "Tres frases: este job hace X porque Y. Sin jerga de adorno.",
        ],
        "hack": [
            "matrix: python-version: [3.11, 3.12] o similar.",
            "environment: production con required reviewers. El artefacto es el de staging, no un rebuild.",
        ],
        "encore": ("Un verde que miente menos", "Pipeline que corre un test unitario de 5 líneas. Hazlo fallar una vez a propósito y pega la captura roja y la verde.", "En Actions: on push, un step que ejecuta pytest o go test. El test puede ser assert 1+1==2 y luego lo rompes."),
    },
    "10": {
        "lecture": [
            ("De verde/rojo a las tres señales", "Para tu app de lab, nombra una métrica, un log y una traza que te gustaría ver.", "Métrica: peticiones/minuto. Log: error con request_id. Traza: el GET que tocó api y base de datos."),
            ("Qué montar", "¿Qué pondrías en un tablero que un extraño entiende en 30 segundos?", "¿Está vivo? ¿Va lento? ¿Hay errores? Cuatro paneles, no cuarenta. La alerta tiene que decir qué hacer."),
        ],
        "shorts": ("Los tres pilares, sin la palabra «observabilidad».", "Números en el tiempo, frases que escribió la app, el camino de una petición. Eso es métrica, log, traza."),
        "walk": ("Anota una alerta tonta pero útil y la acción humana que implica.", "«Error rate > 5% 5 min» → mirar logs con request_id, no reiniciar a ciegas. Si no hay acción, no es alerta: es ruido."),
        "std": [
            "Grafana o un HTML feo: 4 números. Captura de pantalla en el README.",
            "Un middleware que loguee id. Tres líneas con el mismo id en el pegado.",
            "PromQL o equivalente + un párrafo «si dispara, mira…».",
            "Media página. Título, síntomas, primer comando, escalación.",
        ],
        "hack": [
            "Tres métricas en un endpoint. Nombres claros: http_requests_total.",
            "Dos procesos, un traceparent. Jaeger o Tempo local.",
        ],
        "encore": ("Pulso", "Un script que haga curl a una URL cada 10 s y escriba OK/FAIL con fecha en un log.", "while true; do curl -sf URL && echo OK || echo FAIL; sleep 10; done. No hace falta Prometheus para sentir el pulso."),
    },
    "11": {
        "lecture": [
            ("Elige uno y baja a tierra", "Elige AWS, Azure o GCP y escribe el equivalente de: identidad, red, máquina.", "AWS: IAM, VPC, EC2. Azure: Entra ID, VNet, VM. GCP: IAM, VPC, GCE. El mapa se parece; los nombres no."),
            ("Lo que debes practicar", "Nombra tres cosas que apagarías hoy para no llevarte una factura sorpresa.", "VMs, IPs elásticas, load balancers, clusters. El lab no es prod. Budget alert el día 1."),
        ],
        "shorts": ("IaaS vs PaaS vs SaaS con el ejemplo de «quiero una web».", "IaaS: tú la VM. PaaS: tú el código, ellos el runtime. SaaS: usas el producto (el correo, el board)."),
        "walk": ("Escribe los 5 pasos para destruir tu lab. Si no puedes, el lab es una mascota.", "1. snapshot si hace falta. 2. borrar VM. 3. disco. 4. IP. 5. VPC. terraform destroy si llegaste con IaC."),
        "std": [
            "Caja: root/global admin con MFA. Usuario diario. Un rol de lab. Dibujo en texto.",
            "Pública: el balanceador o un bastion. Privada: la app. Una flecha de tráfico.",
            "Una VM o App Service/Cloud Run. 5 pasos de destroy en el README.",
            "Pega el estimador o la consola de costos. Cero «no sé».",
        ],
        "hack": [
            "El .tf de la semana 8 ahora tiene un provider real. plan en el README, apply con presupuesto.",
            "Dos zonas, un LB. Para una instancia: el health check debe fallar y el tráfico irse.",
        ],
        "encore": ("Cuenta de lab", "Activa MFA en la cuenta raíz/global y crea un usuario de diario. Escríbelo en tres líneas.", "No uses la raíz para practicar. Si el proveedor insiste en tarjeta, pon un presupuesto de 1 USD y una alarma."),
    },
    "12": {
        "lecture": [
            ("El ciclo y el ritual", "¿Dónde entra DevOps en tu SDLC, no como slogan, sino en una fase concreta?", "En construcción: CI. En operación: monitoreo y postmortem. En diseño: historias que se pueden probar. No «en todas partes» sin ejemplo."),
            ("Comunicación y troubleshooting", "Escribe el título de un postmortem sin culpas.", "«Caída de 20 min en checkout por timeout a pagos, 17 sep». Nombres de sistemas, no de personas."),
        ],
        "shorts": ("Built-in quality: un ejemplo que no sea «hay que testear más».", "El test corre en el PR. El linter bloquea el merge. La calidad no es una fase del viernes."),
        "walk": ("Convierte una tarea vaga («mejorar el login») en una historia con criterio de aceptación.", "Como usuario, quiero X para Y. Aceptación: dado/cuando/entonces comprobable. Si no se puede probar, no es historia: es un deseo."),
        "std": [
            "Una tabla: fase | práctica DevOps. Cinco filas bastan.",
            "Tres historias. Cada una con un entonces medible (código 200, mail enviado, etc.).",
            "Un test de CI y por qué ahí y no en la laptop del martes.",
            "Timeline, impacto, qué salió bien, acciones con dueño. Cero «fulano se equivocó».",
        ],
        "hack": [
            "Cajas: idea → prod. Marca esperas. Una espera recortable con un número.",
            "Objetivo, hipótesis, inyección de fallo, quién observa, cómo se para. 1 hora, no un simulacro de guerra.",
        ],
        "encore": ("Historia de verdad", "Escribe UNA historia de usuario de tu lab con criterio de aceptación que un test podría fallar.", "«Dado un README vacío, cuando corro el script, entonces sale uso y código 1». Eso se puede automatizar."),
    },
    "13": {
        "lecture": [
            ("Izquierda, pero con juicio", "¿Qué control meterías en el PR y cuál dejarías para staging? Uno de cada.", "PR: secretos y SAST barato. Staging: DAST, imagen firmada. No bloquees el merge con un scan de 40 minutos el día 1."),
        ],
        "shorts": ("SAST vs DAST vs SCA, una línea cada uno.", "SAST: el código quieto. DAST: la app corriendo. SCA: lo que importaste (dependencias)."),
        "walk": ("Pega un hallazgo de un scan (aunque sea de ejemplo) y decide: ¿aceptar, parchar o mitigar?", "CVE en una lib de test ≠ CVE en la imagen de prod. Escribe por qué. «Lo ignoro» no es una decisión: es un olvido."),
        "std": [
            "gitleaks o un regex de AKIA… en CI. Un archivo de ejemplo que debe fallar (sin claves reales).",
            "trivy image … Pega un CVE y tu decisión en una frase.",
            "Amenaza | control. Tres filas. Ejemplo: secreto en repo | pre-commit + rotación.",
            "Un párrafo. «No root, no :latest, no 0.0.0.0:22 abierto al mundo».",
        ],
        "hack": [
            "cosign sign y cosign verify. Si no hay registry, documenta el flujo con comandos.",
            "Un YAML de Kyverno/OPA: privileged: true → deny. kubectl apply y un pod que rebote.",
        ],
        "encore": ("El secreto que no se sube", "Crea un .env de mentira, añádelo a .gitignore, y demuestra que git status no lo ve. Luego un hook o CI que falle si aparece AWS_SECRET.", "echo .env >> .gitignore. git check-ignore -v .env. El CI puede ser un grep en el pipeline, no un producto caro."),
    },
}

